### ISSUE TITLE
Chronological Feed Bug?

### ISSUE THREAD

**Issue by MarkEdward** [mayfield/sauce#8]
Hi, nice work on the plugin, but have you found any problems with the chronological feed? I'm seeing activities from yesterday mixed in between activities from today.

Is this down to upload dates possibly? (Obviously I'm posting an issue before bothering to look at the code, like the lazy sod I am!) 

I'd also (guess) that this is probably quite a hard feature to achieve, as Strava's magic ordering dishes them out to the page in such a messy way (chronologically speaking) that it would be tough to perfectly apply chronological sorting retroactively?

**Comment by mayfield** [comment]
No worries on source code review! :smile: 

It's probably (hopefully) as you suspected that the upload date from those few folks is more recent compared to the time when the activity was ridden.  In the case of manual uploads this could just be delayed by how long it took the user to get to a computer.

The only consistent timestamp value I can find to work with (that isn't based on locale specific strings) is the `updatedAt` timestamp, which I believe corresponds to upload time and possibly last edited time (if that's even possible).

And with regards to your last statement, you're correct.  The sorting is based on the currently available activity feed.  So I sort it chronologically but I can't tell strava to give me the feed as such.  So in some rare cases you would need to scroll down the list, load more activities to get newer entries to show up at towards the top.  Unfortunately the only workaround would be to ask the activity feed to page in many more activities in the hopes of working around their popularity sorting.  Sucks, but I figure what I have is better than nothing?

**Comment by mayfield** [comment]
@MarkEdward let me know if you think were on the same page and I can close this issue.  If you think there is still an issue let me know.

**Comment by MarkEdward** [comment]
Hi Justin, please feel free to close it. 

Your description of the `updateAt` field explained what I was seeing perfectly. Thanks for the reply.

PS - I've not really contributed to many projects on GitHub, but as a web developer with a keen interest in Strava, I'd be happy to help with the project if you've got any (small-ish) outstanding feature ideas?

**Comment by mayfield** [comment]
Hey @MarkEdward I actually found a way to sort by start time or updated (upload) time.  So the next release (or current firefox release) will have an option to choose either one.

Cheers!

PS: I'll ping you if I ever get a demonstrable task list going. :)   Right now I'm just trying to add good Firefox mobile support so I'm hacking and slashing quite a bit.
